// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autocomplete': string;
  'input': string;
  'item': string;
  'itemHover': string;
  'list': string;
}
export const cssExports: CssExports;
export default cssExports;
