// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'labBar': string;
  'list': string;
  'page': string;
}
export const cssExports: CssExports;
export default cssExports;
