// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnCreateTopology': string;
  'cardList': string;
  'container': string;
  'galleryExplication': string;
  'search': string;
  'searchInput': string;
}
export const cssExports: CssExports;
export default cssExports;
