// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn_createTopology': string;
  'cardList': string;
  'galleryExplication': string;
}
export const cssExports: CssExports;
export default cssExports;
