// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconButton': string;
  'textButton': string;
}
export const cssExports: CssExports;
export default cssExports;
