// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'disabled': string;
  'expand': string;
  'menu': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
