// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'settingButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
