// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'slider': string;
  'switch': string;
}
export const cssExports: CssExports;
export default cssExports;
