// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'expanded': string;
  'head': string;
  'list': string;
}
export const cssExports: CssExports;
export default cssExports;
