// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ParameterContainer': string;
  'container': string;
  'header': string;
  'headerTitle': string;
  'label': string;
  'page': string;
  'select': string;
  'storagePlaceInput': string;
}
export const cssExports: CssExports;
export default cssExports;
