// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnChooseDir': string;
  'centerDiv': string;
  'gridItemButton': string;
  'gridItemLeft': string;
  'gridItemRight': string;
  'gridItemTitle': string;
  'header': string;
  'headerTitle': string;
  'label': string;
  'left': string;
  'page': string;
  'select': string;
  'settingsContainer': string;
  'settingsGrid': string;
  'settingsMenu': string;
  'settingsMenuTitle': string;
  'storagePlaceInput': string;
}
export const cssExports: CssExports;
export default cssExports;
