// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnChooseDir': string;
  'centerDiv': string;
  'gridItemLeft': string;
  'gridItemRight': string;
  'label': string;
  'page': string;
  'parameterGrid': string;
  'select': string;
  'storagePlaceInput': string;
}
export const cssExports: CssExports;
export default cssExports;
