// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnList': string;
  'clickable': string;
  'input': string;
  'left': string;
  'separator': string;
  'titleBar': string;
}
export const cssExports: CssExports;
export default cssExports;
