// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backBtn': string;
  'badge': string;
  'btnList': string;
  'center': string;
  'clickable': string;
  'clicked': string;
  'input': string;
  'left': string;
  'separator': string;
  'title': string;
  'titleBar': string;
}
export const cssExports: CssExports;
export default cssExports;
