// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dialog': string;
  'dialog__body': string;
  'dialog__footer': string;
  'dialog__header': string;
}
export const cssExports: CssExports;
export default cssExports;
