// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonAddInterface': string;
  'buttonDelInterface': string;
  'form': string;
  'hideDeviceForm': string;
  'iconWarning': string;
  'image': string;
  'inputDeviceName': string;
  'inputForm': string;
  'inputListCommands': string;
  'label': string;
  'labelForm': string;
  'labelMenu': string;
  'labelTest': string;
  'menuOptionsParameters': string;
  'panel': string;
  'title': string;
  'toggleExpand': string;
  'toolType': string;
  'typeDevice': string;
}
export const cssExports: CssExports;
export default cssExports;
