// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'form': string;
  'image': string;
  'labelInput': string;
  'panel': string;
  'title': string;
  'toggleExpand': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
