// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'divSwitch': string;
  'form': string;
  'image': string;
  'inputConfigPanel': string;
  'ip': string;
  'labelForm': string;
  'labelMenu': string;
  'panel': string;
  'title': string;
  'toggleExpand': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
