import {LocalizationName} from "./index";
import * as RegexConst from "../lib/RegexConst";

export const en : Record<LocalizationName, string> = {
    [LocalizationName.action]: "Action",
    [LocalizationName.command]: "Command",
    [LocalizationName.galleryExplication]: "Hello, select or add a topology to view it",
    [LocalizationName.titleGallery]: "Gallery",
    [LocalizationName.titlePlayground]: "Playground",
    [LocalizationName.titleHeader]: "Project Katara",
    [LocalizationName.EN]: "English",
    [LocalizationName.FR]: "French",
    [LocalizationName.globalSettings]: "Global Settings",
    [LocalizationName.keybindSettings]: "Keybind",
    [LocalizationName.languageParameterLabel]: "Language",
    [LocalizationName.save]: "Save",
    [LocalizationName.storagePlaceLabel]: "Storage place",
    [LocalizationName.themeParameterLabel]: "Theme",
    [LocalizationName.themeLight]: "Light theme",
    [LocalizationName.themeDark]: "Dark theme",
    [LocalizationName.titleGallery]: "Gallery",
    [LocalizationName.titlePlayground]: "Playground",
    [LocalizationName.titleSettings]: "Settings",
    [LocalizationName.themeDark2]: "Dark theme 2",
    [LocalizationName.exportlabNameError]: "Can't export lab, be sure lab name doesn't have more than 32 characters and specials characters, only '' and '-' are allowed",
    [LocalizationName.exportdeviceNameError]: "Can't export lab, be sure devices name doesn't have more than 32 characters and specials characters",
    [LocalizationName.exportInterfaceNameError]: "Can't export lab, be sure interfaces name doesn't have more than 32 characters and specials characters",
    [LocalizationName.exportCollisionDomainError]: "Can't export lab, be sure collision domains doesn't have more than 32 characters and specials characters",
    [LocalizationName.exportlabParameterError32]: " with more than 32 characters not allowed, can't export lab",
    [LocalizationName.exportlabParameterError128]: " with more than 128 characters not allowed, can't export lab",
    [LocalizationName.exportlabParameterError256]: " with more than 256 characters not allowed, can't export lab",
    [LocalizationName.exportlabParameterIntergerError]: "must be an integer, can't export lab",
    [LocalizationName.exportlabParameterIPError]: "Can't export lab, be sure IP are valid",
    [LocalizationName.exportlabParameterCIDRError]: "Can't export lab, be sure CIDR are valid",
    [LocalizationName.exportSuccessFully]: "The lab has been successfully exported",
    [LocalizationName.exportError]: "An error occurred, the lab can't be exported",
    [LocalizationName.importSuccessFully]: "The lab has been successfully imported",
    [LocalizationName.importDirectoryError]: "No directory selected",
    [LocalizationName.titleSearch]: "Search a lab",
    [LocalizationName.newLab]: "New",
    [LocalizationName.openLab]: "Open",
    [LocalizationName.saveLab]: "Save",
    [LocalizationName.importLab]: "Import",
    [LocalizationName.exportLab]: "Export",
    [LocalizationName.duplicateLab]: "Duplicate",
    [LocalizationName.warning]: "Warning"
}
