import {LocalizationName} from "./index";

export const fr : Record<LocalizationName, string> = {
    [LocalizationName.action]: "Action",
    [LocalizationName.command]: "Commande",
    [LocalizationName.galleryExplication]: "Bonjour, sélectionnez ou ajoutez une topologie pour la visualiser",
    [LocalizationName.titleGallery]: "Gallerie",
    [LocalizationName.titlePlayground]: "Terrain de jeu",
    [LocalizationName.titleHeader]: "Projet Katara",
    [LocalizationName.EN]: "Anglais",
    [LocalizationName.FR]: "Français",
    [LocalizationName.globalSettings]: "Paramètres globaux",
    [LocalizationName.keybindSettings]: "Raccourci clavier",
    [LocalizationName.languageParameterLabel]: "Langue",
    [LocalizationName.save]: "Sauvegarder",
    [LocalizationName.storagePlaceLabel]: "Espace de stockage",
    [LocalizationName.themeParameterLabel]: "Thème",
    [LocalizationName.themeLight]: "Thème claire",
    [LocalizationName.themeDark]: "Thème sombre",
    [LocalizationName.titleGallery]: "Gallerie",
    [LocalizationName.titlePlayground]: "Terrain de jeu",
    [LocalizationName.titleSettings]: "Paramètres",
    [LocalizationName.themeDark2]: "Dark theme 2",
    [LocalizationName.exportlabNameError]: "Impossible d'exporter le lab, soyez sur que le nom du lab ne dépasse pas 32 charatères et ne contient pas de charactères spéciaux '_' and '-' sont autorisés",
    [LocalizationName.exportdeviceNameError]: "Impossible d'exporter le lab, soyez sur que les nom des machines ne dépasses pas 32 charatères et ne contienent pas de charactères spéciaux",
    [LocalizationName.exportInterfaceNameError]: "Impossible d'exporter le lab, soyez sur que les nom des interfaces ne dépasses pas 32 charatères et ne contienent pas de charactères spéciaux",
    [LocalizationName.exportCollisionDomainError]: "Impossible d'exporter le lab, soyez sur que les domaines de collision ne dépasses pas 32 charatères et ne contienent pas de charactères spéciaux",
    [LocalizationName.exportlabParameterError32]: "avec plus de 32 caractères n'est pas autorisé, export annulé",
    [LocalizationName.exportlabParameterError128]: "avec plus de 128 caractères n'est pas autorisé, export annulé",
    [LocalizationName.exportlabParameterError256]: "avec plus de 256 caractères n'est pas autorisé, export annulé",
    [LocalizationName.exportlabParameterIntergerError]: "doit être un entier, export annulé",
    [LocalizationName.exportlabParameterIPError] : "Impossible d'exporter le lab, soyez sur que que les adresses IP sont valides",
    [LocalizationName.exportlabParameterCIDRError] : "Impossible d'exporter le lab, soyez sur que que les adresses CIDR sont valides",
    [LocalizationName.exportSuccessFully] : "Le lab a été exporté avec succès",
    [LocalizationName.exportError] : "Une erreur est survenue, impossible d'exporter le lab",
    [LocalizationName.importSuccessFully] : "Le lab a été importé avec succès",
    [LocalizationName.importDirectoryError] : "Aucun répertoire selectionné",
}
