// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'snackbar': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
