// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'cardTitle': string;
  'img': string;
}
export const cssExports: CssExports;
export default cssExports;
