// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'section': string;
  'section__title': string;
}
export const cssExports: CssExports;
export default cssExports;
