name: Release
on: [workflow_dispatch]

jobs:

  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: generate files
        run: |
          npm run start & sleep 30
          kill -INT %+
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: generate files
        run: |
          npm run start & sleep 30
          kill -INT %+
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: generate files
        run: |
          Start-Process -FilePath "npm.exe" -ArgumentList "run start" -NoNewWindow -Wait
          Start-Sleep -Seconds 30
          Stop-Process -Id (Get-Process -Name "node" -ErrorAction SilentlyContinue).Id -Force
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish
